version: '3.10'
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    
  main:
    restart: always
    build: ./backend/main
    ports:
      - '8080:8080'
    depends_on:
      - decisionengine
      - accounting

  accounting:
    restart: always
    build: ./backend/accounting
    ports:
      - '8081:8081'  

  decisionengine:
    restart: always
    build: ./backend/decisionEngine
    ports:
      - '8082:8082'